//
// Created by Roy Noyman on 02/12/2021.
//

#ifndef UNTITLED_MESSAGE_SLOT_H
#define UNTITLED_MESSAGE_SLOT_H

#endif //UNTITLED_MESSAGE_SLOT_H
#define MAJOR_NUMBER 240
#define BUFFER_LENGTH 128
#define MAX_MINORS 256
#define MY_CHAR_DEV "MY_CHAR_DEV"
